### ISSUE TITLE
Your Code is not Feasible 

### ISSUE THREAD

**Issue by hrithikksingh3** [ShivenPokhriyal/Calculator#1]
Your code is not Feasible since you have uploaded snapshots of the codes instead of actual code files.
It can be easily solved you are just one more commit away. 

These two repositories have this issue.
[https://github.com/ShivenPokhriyal/Income-Tax-Calculator]
[https://github.com/ShivenPokhriyal/Income-Tax-Calculator]

**Comment by ShivenPokhriyal** [comment]
I will check

**Comment by hrithikksingh3** [comment]
Okk
